# Tree Processing
For this study, trees were modeled as if they were 'buildings' but with a high wall absorption coefficient.

# Glasgow Tree Processing
Data:  https://data.ubdc.ac.uk/dataset/96ad6074-acff-49fc-95da-473fe6da4205

## Reading all the files into 1 gdf

In [261]:
import geopandas as gpd
import pandas as pd
import glob
import os

# Folder containing the shapefiles
folder_path = r"C:\Users\ibk1\NoiseModelling\Glasgow\env_data\tree_volume\tree_canopy_products\treetop_location"

# Get a list of all shapefiles in the folder
shapefiles = glob.glob(os.path.join(folder_path, "*.shp"))

# Read and process each shapefile
gdfs = [gpd.read_file(shp).set_crs(epsg=27700, allow_override=True) for shp in shapefiles]

# Merge all shapefiles into a single GeoDataFrame
merged_gdf = gpd.GeoDataFrame(pd.concat(gdfs, ignore_index=True))

# Create a 0.5-meter buffer around each point
merged_gdf["geometry"] = merged_gdf.geometry.buffer(1) # This sets the average diameter to 1 (0.5m, 50cm radius), might be too large 

print(f"Merged and buffered gdf created!")

Merged and buffered gdf created!

In [336]:
len(merged_gdf)

1339588

In [337]:
merged_gdf.head()

     HEIGHT                                           THE_GEOM    G
0  9.662998  POLYGON ((249624.25 659999.865, 249624.245 659...  0.1
1  6.701000  POLYGON ((249627.75 659999.865, 249627.745 659...  0.1
2  9.841003  POLYGON ((249501.25 659999.365, 249501.245 659...  0.1
3  6.231998  POLYGON ((249532.25 659999.365, 249532.245 659...  0.1
4  4.015003  POLYGON ((249982.75 659999.365, 249982.745 659...  0.1

In [346]:
merged_gdf["HEIGHT"].median()

9.642999649047852

In [263]:
merged_gdf.columns
merged_gdf = merged_gdf[['Z', "geometry"]]
merged_gdf = merged_gdf[['Z', 'geometry']].rename(columns={'Z': 'HEIGHT', 'geometry': 'THE_GEOM'})
merged_gdf["G"] = .1 # Wall absorption

In [264]:
merged_gdf = merged_gdf.set_geometry("THE_GEOM")

In [265]:
merged_gdf.head()

     HEIGHT                                           THE_GEOM    G
0  9.662998  POLYGON ((249624.25 659999.865, 249624.245 659...  0.1
1  6.701000  POLYGON ((249627.75 659999.865, 249627.745 659...  0.1
2  9.841003  POLYGON ((249501.25 659999.365, 249501.245 659...  0.1
3  6.231998  POLYGON ((249532.25 659999.365, 249532.245 659...  0.1
4  4.015003  POLYGON ((249982.75 659999.365, 249982.745 659...  0.1

In [266]:
merged_gdf.to_file(r"C:\Users\ibk1\NoiseModelling\Glasgow\noisemodelling_outputs\summerbuildings\trees.geojson")

## Combining with Buildings

In [347]:
import geopandas as gpd
buildings = gpd.read_file(r"C:\Users\ibk1\NoiseModelling\Glasgow\noisemodelling_outputs\Round2\ready_input_buildings_cleaned.geojson") # Changed to a different srid 
buildings.columns

Index(['PK', 'HEIGHT', 'geometry'], dtype='object')

In [348]:
len(buildings)

61466

In [364]:
test = buildings[buildings["HEIGHT"] < 0]

In [365]:
test.explore()

In [314]:
buildings.columns

Index(['PK', 'HEIGHT', 'geometry'], dtype='object')

In [315]:
buildings.head()

   PK     HEIGHT                                           geometry
0   1  53.230999  POLYGON ((251523.28 672118.14, 251519.33 67210...
1   2  52.737000  POLYGON ((251502.32 672114.01, 251503.54 67211...
2   3  53.498001  POLYGON ((251539.19 672102.32, 251530.49 67209...
3   4  52.759998  POLYGON ((251488.03 672078.03, 251483.36 67208...
4   5  49.250000  POLYGON ((251403.66 672074.72, 251402.21 67207...

In [316]:
# Changing geometry names to match case with noisemodelling 
#buildings = buildings[['Ground_Z', "geometry"]]
#buildings = buildings[['Ground_Z', 'geometry']].rename(columns={'Ground_Z': 'HEIGHT', 'geometry': 'geometry'})

In [317]:
buildings["G"] = .9 # Wall absorption

In [318]:
buildings.head()

   PK     HEIGHT                                           geometry    G
0   1  53.230999  POLYGON ((251523.28 672118.14, 251519.33 67210...  0.9
1   2  52.737000  POLYGON ((251502.32 672114.01, 251503.54 67211...  0.9
2   3  53.498001  POLYGON ((251539.19 672102.32, 251530.49 67209...  0.9
3   4  52.759998  POLYGON ((251488.03 672078.03, 251483.36 67208...  0.9
4   5  49.250000  POLYGON ((251403.66 672074.72, 251402.21 67207...  0.9

In [320]:
trees_clean = gpd.read_file(r"C:\Users\ibk1\NoiseModelling\Glasgow\noisemodelling_outputs\summerbuildings\trees_clean.geojson")

In [321]:
trees_clean.head()

   PK    HEIGHT                                           geometry
0   1  9.662998  POLYGON ((249623.81 659999.03, 249623.15 65999...
1   2  6.701000  POLYGON ((249627.75 659999.77, 249627.31 65999...
2   3  9.841003  POLYGON ((249500.81 659998.53, 249500.15 65999...
3   4  6.231998  POLYGON ((249532.25 659999.27, 249531.81 65999...
4   5  4.015003  POLYGON ((249982.75 659999.27, 249982.31 65999...

In [322]:
trees_clean["G"] = .1 # Wall absorption

In [323]:
combined_gdf = gpd.GeoDataFrame(pd.concat([trees_clean, buildings], ignore_index=True))

In [324]:
combined_gdf.head()

   PK    HEIGHT                                           geometry    G
0   1  9.662998  POLYGON ((249623.81 659999.03, 249623.15 65999...  0.1
1   2  6.701000  POLYGON ((249627.75 659999.77, 249627.31 65999...  0.1
2   3  9.841003  POLYGON ((249500.81 659998.53, 249500.15 65999...  0.1
3   4  6.231998  POLYGON ((249532.25 659999.27, 249531.81 65999...  0.1
4   5  4.015003  POLYGON ((249982.75 659999.27, 249982.31 65999...  0.1

In [325]:
combined_gdf["G"].unique()

array([0.1, 0.9])

In [326]:
subset = gpd.clip(combined_gdf, bbox)

In [327]:
subset.explore()

In [328]:
len(combined_gdf)

1401054

In [329]:
combined_gdf.columns

Index(['PK', 'HEIGHT', 'geometry', 'G'], dtype='object')

In [330]:
combined_gdf = combined_gdf.drop(columns=['PK'])

In [331]:
combined_gdf = combined_gdf[['HEIGHT', 'geometry', 'G']].rename(columns={'HEIGHT': 'HEIGHT', 'geometry': 'THE_GEOM', 'G': 'G'})

In [332]:
combined_gdf.columns

Index(['HEIGHT', 'THE_GEOM', 'G'], dtype='object')

In [333]:
# Changing geometry names to match case with noisemodelling 
combined_gdf = combined_gdf.set_geometry("THE_GEOM")
# Save as a geojson, note that this is now a 27700
combined_gdf.to_file(r"C:\Users\ibk1\NoiseModelling\Glasgow\noisemodelling_outputs\Round3\trees_final_4.geojson", driver="GeoJSON")

# Edinburgh Trees and Buildings
Data: https://data.edinburghcouncilmaps.info/datasets/6c224ada230b4d349cfd739015c7846d_41/explore

#### buildings layer 
Acquired from OpenStreetMap

In [63]:
import geopandas as gpd
import pandas as pd

In [366]:
nm_edi_buildings = gpd.read_file(r"C:\Users\ibk1\NoiseModelling\Edinburgh\noisemodelling_inputs\buildings\nm_edi_buildings.geojson")

#### setting buildings wall abs to 0.9

In [65]:
nm_edi_buildings["G"] = 0.9 # Adding wall absorption

In [66]:
nm_edi_buildings.head()

,PK,HEIGHT,geometry,G
0,1308683759,6.877683,"POLYGON ((329067.092 667684.922, 329073.301 66...",0.9
1,1308683758,7.579757,"POLYGON ((329060.026 667693.855, 329066.235 66...",0.9
2,1308683757,6.453828,"POLYGON ((329054.707 667703.248, 329060.916 66...",0.9
3,1308683760,6.077773,"POLYGON ((329087.424 667703.825, 329093.633 66...",0.9
4,1308683761,6.119651,"POLYGON ((329082.493 667713.958, 329088.701 66...",0.9

#### reading trees shapefiles

In [334]:
editrees_buff = gpd.read_file(r"C:\Users\ibk1\NoiseModelling\Edinburgh\env_data\Trees\Trees.shp")

In [335]:
len(editrees_buff)

50400

In [339]:
editrees_buff["

Index(['OBJECTID', 'PrimaryKey', 'LocationOr', 'Ward', 'Site', 'LatinName',
       'CommonName', 'Owner', 'NTRef', 'Height', 'Spread', 'AgeGroup',
       'DiameterAt', 'Easting', 'Northing', 'geometry'],
      dtype='object')

#### setting tree values to mid range, setting wall abs to 0.1

In [340]:
import geopandas as gpd
import pandas as pd
from shapely.geometry import Point

height_mapping = {
    "5 to 10 meters": 7.5,
    "10 to 15 meters": 12.5,
    "15 to 20 meters": 17.5,
    "20 to 25 meters": 22.5,
    "25 to 30 meters": 27.5,
    "Up to 5 meters": 4.5,
    "30 meters +": 32,
}

# Function to map height values
def extract_height(value):
    if pd.isna(value) or value is None:
        return None  # Keep NaN values

    value = str(value).strip()  # Convert to string and remove extra spaces
    
    if value in height_mapping:
        return height_mapping[value]  # Use predefined mapping
    
    return None  # If value is not found in mapping, return NaN
# Apply functions to extract values
editrees_buff["HEIGHT"] = editrees_buff["Height"].apply(extract_height)  # Tree height (meters)
editrees_buff["G"] = .1 # Wall absorption

In [344]:
editrees_buff["HEIGHT"].describe()

count    49996.000000
mean        10.097528
std          5.501568
min          4.500000
25%          4.500000
50%          7.500000
75%         12.500000
max         32.000000
Name: HEIGHT, dtype: float64

#### creating geometry buffer of 1 meter 
setting avg height for nan to 5 m

In [69]:
editrees_buff["geometry"] = editrees_buff.geometry.buffer(1)
editrees_buff['HEIGHT'] = editrees_buff['HEIGHT'].fillna(5)

#### combining trees and nm buildings

In [70]:
# Combine both GeoDataFrames
merged_gdf_buff = gpd.GeoDataFrame(pd.concat([editrees_buff, nm_edi_buildings], ignore_index=True))

# Ensure it remains a GeoDataFrame and retains geometries
merged_gdf_buff = gpd.GeoDataFrame(merged_gdf_buff, geometry="geometry", crs="EPSG:27700")

In [71]:
print(len(nm_edi_buildings), len(editrees_buff), len(merged_gdf_buff))

158826 50400 209226

In [49]:
merged_gdf_buff.head()

,OBJECTID,PrimaryKey,LocationOr,Ward,Site,LatinName,CommonName,Owner,NTRef,Height,Spread,AgeGroup,DiameterAt,Easting,Northing,geometry,HEIGHT,G,PK
0,1.0,Grp/1 (845800),None,Inverleith\n,"Raeburn Mews, Edinburgh",None,None,None,NT06-9001-0993,None,None,Over-Mature,None,309001.0,660993.0,"POLYGON ((309002 660993, 309001.995 660992.902...",5.0,0.1,NaN
1,2.0,Sgl/358 (813204),2-205-16,Fountainbridge/Craiglockhart\n,Craiglockhart Woods,None,None,Culture and Leisure,NT06-9010-1010,5 to 10 meters,6 to 9 meters,Juvenile,10 - 20,309010.0,661010.0,"POLYGON ((309011 661010, 309010.995 661009.902...",7.5,0.1,NaN
2,3.0,Sgl/18 (046468),b05936,Drum Brae/Gyle\n,"Rannoch Road, Edinburgh",Acer pseudoplatanus,Sycamore,None,NT17-0000-4261,15 to 20 meters,Over 12 meters,Mature,90 +,310000.0,674261.0,"POLYGON ((310001 674261, 310000.995 674260.902...",17.5,0.1,NaN
3,4.0,Sgl/1274 (071816),g00495,Almond\n,Davidson's Main's Park,Acer pseudoplatanus,Sycamore,Culture and Leisure,NT17-0000-5419,20 to 25 meters,Over 12 meters,Mature,90 +,310000.0,675419.0,"POLYGON ((310001 675419, 310000.995 675418.902...",22.5,0.1,NaN
4,5.0,Sgl/82 (193348),w765,Almond\n,Royal High School,Acer pseudoplatanus,Sycamore,Children and Families,NT17-0000-5184,15 to 20 meters,9 to 12 meters,Mature,50 - 60,310000.0,675184.0,"POLYGON ((310001 675184, 310000.995 675183.902...",17.5,0.1,NaN

#### subsetting to relevant fields

In [50]:
keep_col = ["HEIGHT", "geometry", "G"]
# Keep only the relevant columns
merged_gdf_buff = merged_gdf_buff[keep_col]

In [51]:
merged_gdf_buff.head()

   HEIGHT                                           geometry    G
0     5.0  POLYGON ((309002 660993, 309001.995 660992.902...  0.1
1     7.5  POLYGON ((309011 661010, 309010.995 661009.902...  0.1
2    17.5  POLYGON ((310001 674261, 310000.995 674260.902...  0.1
3    22.5  POLYGON ((310001 675419, 310000.995 675418.902...  0.1
4    17.5  POLYGON ((310001 675184, 310000.995 675183.902...  0.1

In [53]:
merged_gdf_buff["PK"] = range(1, len(merged_gdf_buff)+1)

In [57]:
merged_gdf_buff

,HEIGHT,geometry,G,PK
0,5.000000,"POLYGON ((309002 660993, 309001.995 660992.902...",0.1,1
1,7.500000,"POLYGON ((309011 661010, 309010.995 661009.902...",0.1,2
2,17.500000,"POLYGON ((310001 674261, 310000.995 674260.902...",0.1,3
3,22.500000,"POLYGON ((310001 675419, 310000.995 675418.902...",0.1,4
4,17.500000,"POLYGON ((310001 675184, 310000.995 675183.902...",0.1,5
...,...,...,...,...
209221,5.272708,"POLYGON ((312156.643 678821.294, 312167.928 67...",0.9,209222
209222,5.211208,"POLYGON ((312958.545 678399.613, 312964.718 67...",0.9,209223
209223,4.077840,"POLYGON ((313674.709 678398.168, 313670.064 67...",0.9,209224
209224,5.441919,"POLYGON ((313682.199 678399.765, 313676.993 67...",0.9,209225
209225,4.813933,"POLYGON ((312944.677 678407.208, 312947.843 67...",0.9,209226

In [56]:
merged_gdf_buff.to_file(r"C:\Users\ibk1\NoiseModelling\Edinburgh\noisemodelling_outputs\Round 6\buildings9_trees1_pk.geojson", driver="geoJSON")